export const COFFEE_TEMPLATES = [
  {
    id: 1,
    name: 'ТЦ Мега Белая Дача',
    type: 'coffee',
    template: '3×4',
    rowColumns: [3, 3, 3, 3],
    matrixData: {
      '1-1': { product: 'Американо', price: '120', maxQuantity: '10' },
      '1-2': { product: 'Капучино с молоком', price: '150', maxQuantity: '10' },
      '1-3': { product: 'Латте', price: '160', maxQuantity: '10' },
      '2-1': { product: 'Эспрессо', price: '100', maxQuantity: '10' },
      '2-2': { product: 'Глинтвейн', price: '180', maxQuantity: '10' },
      '2-3': { product: 'Какао', price: '130', maxQuantity: '10' },
      '3-1': { product: 'Чай черный', price: '80', maxQuantity: '10' },
      '3-2': { product: 'Чай зеленый', price: '80', maxQuantity: '10' },
      '3-3': { product: 'Макиато', price: '140', maxQuantity: '10' },
    },
  },
  {
    id: 2,
    name: 'ТРЦ Авиапарк',
    type: 'coffee',
    template: '4×5',
    rowColumns: [4, 4, 4, 4, 4],
    matrixData: {
      '1-1': { product: 'Американо', price: '130', maxQuantity: '10' },
      '1-2': { product: 'Капучино с молоком', price: '160', maxQuantity: '10' },
      '1-3': { product: 'Латте', price: '170', maxQuantity: '10' },
      '1-4': { product: 'Эспрессо', price: '110', maxQuantity: '10' },
      '2-1': { product: 'Глинтвейн', price: '190', maxQuantity: '10' },
      '2-2': { product: 'Какао', price: '140', maxQuantity: '10' },
      '2-3': { product: 'Чай черный', price: '90', maxQuantity: '10' },
      '2-4': { product: 'Чай зеленый', price: '90', maxQuantity: '10' },
    },
  },
  {
    id: 3,
    name: 'БЦ Москва-Сити',
    type: 'coffee',
    template: '5×6',
    rowColumns: [5, 5, 5, 5, 5, 5],
    matrixData: {
      '1-1': { product: 'Американо', price: '140', maxQuantity: '10' },
      '1-2': { product: 'Капучино с молоком', price: '170', maxQuantity: '10' },
      '1-3': { product: 'Латте', price: '180', maxQuantity: '10' },
      '1-4': { product: 'Эспрессо', price: '120', maxQuantity: '10' },
      '1-5': { product: 'Раф кофе', price: '200', maxQuantity: '10' },
      '2-1': { product: 'Глинтвейн', price: '200', maxQuantity: '10' },
      '2-2': { product: 'Какао', price: '150', maxQuantity: '10' },
      '2-3': { product: 'Чай черный', price: '100', maxQuantity: '10' },
      '2-4': { product: 'Чай зеленый', price: '100', maxQuantity: '10' },
      '2-5': { product: 'Макиато', price: '160', maxQuantity: '10' },
    },
  },
];

export const FRIDGE_TEMPLATES = [
  {
    id: 4,
    name: 'Стандартный холодильник',
    type: 'fridge',
    template: '4×2',
    rowColumns: [4, 4],
    matrixData: {
      '1-1': { product: 'Кола 0.5л', price: '90', maxQuantity: '5' },
      '1-2': { product: 'Спрайт 0.5л', price: '90', maxQuantity: '5' },
      '1-3': { product: 'Фанта 0.5л', price: '90', maxQuantity: '5' },
      '1-4': { product: 'Вода 0.5л', price: '70', maxQuantity: '5' },
      '2-1': { product: 'Снекерс', price: '75', maxQuantity: '5' },
      '2-2': { product: 'Твикс', price: '75', maxQuantity: '5' },
      '2-3': { product: 'Снекерс', price: '75', maxQuantity: '5' },
      '2-4': { product: 'Вода 0.5л', price: '70', maxQuantity: '5' },
    },
  },
  {
    id: 5,
    name: 'Большой холодильник',
    type: 'fridge',
    template: '5×3',
    rowColumns: [5, 5, 5],
    matrixData: {
      '1-1': { product: 'Кола 0.5л', price: '90', maxQuantity: '5' },
      '1-2': { product: 'Спрайт 0.5л', price: '90', maxQuantity: '5' },
      '1-3': { product: 'Фанта 0.5л', price: '90', maxQuantity: '5' },
      '1-4': { product: 'Вода 0.5л', price: '70', maxQuantity: '5' },
      '1-5': { product: 'Кола 0.5л', price: '90', maxQuantity: '5' },
      '2-1': { product: 'Снекерс', price: '75', maxQuantity: '5' },
      '2-2': { product: 'Твикс', price: '75', maxQuantity: '5' },
      '2-3': { product: 'Снекерс', price: '75', maxQuantity: '5' },
      '2-4': { product: 'Твикс', price: '75', maxQuantity: '5' },
      '2-5': { product: 'Снекерс', price: '75', maxQuantity: '5' },
      '3-1': { product: 'Вода 0.5л', price: '70', maxQuantity: '5' },
      '3-2': { product: 'Вода 0.5л', price: '70', maxQuantity: '5' },
      '3-3': { product: 'Фанта 0.5л', price: '90', maxQuantity: '5' },
      '3-4': { product: 'Спрайт 0.5л', price: '90', maxQuantity: '5' },
      '3-5': { product: 'Кола 0.5л', price: '90', maxQuantity: '5' },
    },
  },
  {
    id: 6,
    name: 'Мини холодильник',
    type: 'fridge',
    template: '3×2',
    rowColumns: [3, 3],
    matrixData: {
      '1-1': { product: 'Кола 0.5л', price: '90', maxQuantity: '5' },
      '1-2': { product: 'Спрайт 0.5л', price: '90', maxQuantity: '5' },
      '1-3': { product: 'Фанта 0.5л', price: '90', maxQuantity: '5' },
      '2-1': { product: 'Снекерс', price: '75', maxQuantity: '5' },
      '2-2': { product: 'Твикс', price: '75', maxQuantity: '5' },
      '2-3': { product: 'Вода 0.5л', price: '70', maxQuantity: '5' },
    },
  },
];
